### ISSUE TITLE
ODROID C4 support

### ISSUE THREAD

**Issue by apiraino** [ardera/flutter_packages#4]
hello!

I'm trying to compile and deploy a sample application ODROID C4 but when I run the app it crashes:
```
E/flutter ( 4463): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libc.so.6': dlopen failed: library "libc.so.6" not found
E/flutter ( 4463): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 4463): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter ( 4463): #2      new PlatformInterface._private (package:flutter_gpiod/src/gpiod.dart:189:42)
E/flutter ( 4463): #3      PlatformInterface.instance (package:flutter_gpiod/src/gpiod.dart:240:37)
E/flutter ( 4463): #4      FlutterGpiod.instance (package:flutter_gpiod/src/gpiod.dart:668:43)
E/flutter ( 4463): #5      main (package:marchivum/main.dart:9:30)
E/flutter ( 4463): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:145:25)
E/flutter ( 4463): #7      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 4463): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4463): #9      _runZoned (dart:async/zone.dart:1863:10)
E/flutter ( 4463): #10     runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter ( 4463): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
E/flutter ( 4463): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 4463): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 4463): 
Syncing files to device ODROID C4...                                90ms
```

Do I need to install anything on my development machine (like, the Android NDK?). Is the ODROID C4 supported?

thanks!

**Comment by ardera** [comment]
I think this is working now.

**Comment by apiraino** [comment]
confirmed (and sorry for getting back to you)

thank you @ardera so much for your help :)
